// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProgettoIDS.Data;

#nullable disable

namespace ProgettoIDS.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220516115712_CreazioneDatabase")]
    partial class CreazioneDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");
#pragma warning restore 612, 618
        }
    }
}
